name: kontext_flutter_sdk
description: Flutter SDK for integrating Kontext.so ads. Monetize text-based & AI apps like chatbots, search or messaging with unique, native ad formats.
version: 1.1.2
homepage: https://www.kontext.so/publishers
repository: https://github.com/kontextso/sdk-flutter
issue_tracker: https://github.com/kontextso/sdk-flutter/issues
documentation: https://docs.kontext.so/sdk/flutter
license: Apache-2.0

platforms:
  android:
  ios:

topics:
  - ads
  - sdk
  - flutter
  - monetization

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  device_info_plus: ^11.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_inappwebview: ^6.1.5
  http: ^1.4.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_hooks_test: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: so.kontext.sdk.flutter
        pluginClass: KontextSdkPlugin
      ios:
        pluginClass: KontextSdkPlugin
